# This is a basic workflow to help you get started with Actions

name: Auto-deploy release

# Controls when the action will run. 
on:
  # New release published
  release:
    types: [published]
  # Manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployments

    # Sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup server access 1
        run: mkdir $HOME/.ssh
        shell: bash

      - name: setup server access 2
        env:
          WEB_SERVER_SSH_KEY: ${{ secrets.WEB_SERVER_SSH_KEY }}
        run: 'printf "$WEB_SERVER_SSH_KEY" > $HOME/.ssh/id_webserver'
        shell: bash

      - name: setup server access 3
        run: chmod 600 $HOME/.ssh/id_webserver
        shell: bash

      - name: setup server access 4
        env:
          WEB_SERVER_HOST: ${{ secrets.WEB_SERVER_HOST }}
        run: 'ssh-keyscan -H $WEB_SERVER_HOST > $HOME/.ssh/known_hosts'
        shell: bash

      - name: rsync the files to the server
        env:
          WEB_SERVER_HOST: ${{ secrets.WEB_SERVER_HOST }}
        run: rsync -avz -e "ssh -i $HOME/.ssh/id_webserver" --exclude-from=.rsyncignore ./* matt@$WEB_SERVER_HOST:/var/www/threadguide/
        working-directory: ${{ github.workspace }}
        shell: bash
